baseURL = "https://neilcameron.me"
languageCode = "en-gb"
title = "London tech guy: rails, agile, tech, startups."
theme = "bootstrap"
enableRobotsTXT = true
googleAnalytics = "UA-62883841-3"
disqusShortname = "neilcameronme"

[social]
twitter = "ncameron"


[imaging]
  resampleFilter = "box"
  quality = 90
  anchor = "smart"

[Params]
	DateForm = "12 Jan 2006"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/#about"
    weight = 1

  [[menu.main]]
    name = "How I can help"
    url = "/#help"
    weight = 2

  [[menu.main]]
    name = "Recent work"
    url = "/#recent"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 5