baseURL = "https://neilcameron.me"
languageCode = "en-us"
title = "London consultant: rails, agile, drupal, tech, startups."
theme = "bootstrap"
enableRobotsTXT = true
googleAnalytics = "UA-62883841-3"

[imaging]
  resampleFilter = "box"
  quality = 90
  anchor = "smart"

[Params]
	DateForm = "12 Jan 2006"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    pre = "<i class='fa fa-heart'></i>"
    url = "/#about"
    weight = 1

  [[menu.main]]
    name = "How I can help"
    pre = "<i class='fa fa-road'></i>"
    url = "/#help"
    weight = 2

  [[menu.main]]
    name = "Recent work"
    pre = "<i class='fa fa-road'></i>"
    url = "/#recent"
    weight = 3

  [[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-road'></i>"
    url = "/#blog"
    weight = 4

  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-road'></i>"
    url = "/#contact"
    weight = 5